// Generated by gen-config.mjs (local) from ../.data/addresses.local.json. Do not edit by hand.
export const NON_HOLDERS: ReadonlySet<string> = new Set(["0x000000000000000000000000000000000000dead","0x7050cfbb7be07f103bffb08c9c1d38e654ade000","0xf83063df4338ca22b3aa237760fdc25b94dbada3","0x2e5290215f48fed630a9d1b6205a3cc82c44aab5"]);
