// Writes config.yaml from a KOMA deployment file.
//   node gen-config.mjs local    → ../.data/addresses.local.json, indexing the local anvil fork over RPC
//   node gen-config.mjs testnet  → ../deploy/addresses.10143.json, Monad testnet over HyperSync (10143.hypersync.xyz)
import { readFileSync, writeFileSync } from "node:fs";

const target = process.argv[2] ?? "local";
const file = target === "local" ? "../.data/addresses.local.json" : `../deploy/addresses.${target === "testnet" ? 10143 : 143}.json`;
const a = JSON.parse(readFileSync(file, "utf8"));
const rpc = target === "local" ? process.env.ENVIO_RPC_URL ?? "http://127.0.0.1:18643" : null;

const yaml = `# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
# Generated by gen-config.mjs (${target}) from ${file}. Do not edit by hand.
name: koma-indexer
description: KOMA on Monad — series, trades, holders, canon, backers
field_selection:
  transaction_fields: [hash]
contracts:
  - name: SeriesFactory
    events:
      - event: SeriesLaunched(uint256 indexed seriesId, address indexed creator, address coin, address curve, uint256 characterId, address characterAccount, uint256 parentSeriesId, uint256 graduationTarget, string name, string symbol)
  - name: BondingCurve
    events:
      - event: Trade(address indexed trader, bool indexed isBuy, uint256 usdcAmount, uint256 coinAmount, uint256 fee, uint256 vU, uint256 vC, uint256 raised)
      - event: Completed(uint256 raised)
      - event: Graduated(address pool, bytes32 poolId, uint256 usdcToPool, uint256 coinToPool)
  - name: SeriesCoin
    events:
      - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: CanonRegistry
    events:
      - event: Proposed(uint256 indexed seriesId, uint256 indexed episode, uint256 indexed issueId, address proposer)
      - event: SlotOpened(uint256 indexed seriesId, uint256 indexed episode, uint64 snapshot, uint64 endsAt)
      - event: CanonFinalized(uint256 indexed seriesId, uint256 indexed episode, uint256 winnerIssueId, bytes32 votesRoot, uint256 winnerVotes, uint256 totalVotes)
  - name: RoyaltyRouter
    events:
      - event: Routed(uint256 indexed seriesId, address indexed recipient, uint256 amount, uint8 kind)
  - name: Graduator
    events:
      - event: PoolCreated(uint256 indexed seriesId, bytes32 poolId, uint160 sqrtPriceX96, uint256 usdcToPool, uint256 coinToPool, uint256 liquidity)
      - event: GraduationFee(uint256 indexed seriesId, uint256 usdcFee)
  - name: KomaSwapper
    events:
      - event: Swapped(uint256 indexed seriesId, address indexed payer, address indexed recipient, bool buyCoin, uint256 amountIn, uint256 amountOut)
  - name: KomaIssues
    events:
      - event: IssueMinted(uint256 indexed tokenId, address indexed to, bytes32 indexed paymentTx, bytes32 contentHash, uint256 remixOf, uint16 pages)
chains:
  - id: ${a.chainId}
    start_block: ${a.deployBlock}
${rpc ? `    rpc:\n      - url: ${rpc}\n        for: sync\n` : ""}    contracts:
      - name: SeriesFactory
        address: [${a.seriesFactory}]
      - name: CanonRegistry
        address: [${a.canonRegistry}]
      - name: RoyaltyRouter
        address: [${a.royaltyRouter}]
      - name: Graduator
        address: [${a.graduator}]
      - name: KomaSwapper
        address: [${a.swapper}]
      - name: KomaIssues
        address: [${a.komaIssues}]
      - name: BondingCurve
      - name: SeriesCoin
`;
writeFileSync("config.yaml", yaml);

// Contract-held balances aren't holders (same rule as the app's own index): the burn address and the v4 side.
const nonHolders = ["0x000000000000000000000000000000000000dead", a.graduator, a.poolManager, a.positionManager].filter(Boolean).map((x) => x.toLowerCase());
writeFileSync(
  "src/deployment.ts",
  `// Generated by gen-config.mjs (${target}) from ${file}. Do not edit by hand.\nexport const NON_HOLDERS: ReadonlySet<string> = new Set(${JSON.stringify(nonHolders)});\n`,
);
console.log(`config.yaml for ${target}: chain ${a.chainId} from block ${a.deployBlock}${rpc ? ` via ${rpc}` : " via HyperSync"}`);
